In [1]:
import pandas as pd

In [9]:
roll = pd.Series([1,2,3])
name = pd.Series(['aarya', 'akshata', 'shreya'])
marks = pd.Series([80, 85, 75])

In [10]:
df = pd.DataFrame({
    'id': roll,
    'name': name,
    'marks':marks
})

In [11]:
df

   id     name  marks
0   1    aarya     80
1   2  akshata     85
2   3   shreya     75

In [12]:
df.ndim

2

In [13]:
df.shape

(3, 3)

In [14]:
df.size

9

In [16]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [1]:
"""
url -> https://mitu.co.in/dataset -> will connect to drive folder

download all the dataset starting with student*
put them in the same file folder as ur current working directory

""";

In [6]:
import urllib.request

url = "https://raw.githubusercontent.com/AdityaThakare72/interns-may-2026/master/daily_codes/week4/student.csv"

urllib.request.urlretrieve(url, "student.csv")

print("Downloaded")

Downloaded

In [7]:
import os
print(os.listdir())

['.anaconda', '.conda', '.continuum', '.copilot', '.idlerc', '.ipynb_checkpoints', '.ipython', '.jupyter', '.matplotlib', '.ms-ad', '.nbi', '.packettracer', '.spyder-py3', '.vscode', '.vscode-shared', '3D Objects', 'a1.ipynb', 'a1.txt', 'a2.ipynb', 'aarya.ipynb', 'aarya.p.py', 'aarya1.ipynb', 'anaconda3', 'AppData', 'Application Data', 'Arrays.ipynb', 'bar figure 3.png', 'bar figure.png', 'bar figured 2.png', 'basics.ipynb', 'Cisco Packet Tracer 7.3.0', 'Cisco Packet Tracer 9.0.0', 'Codes.ipynb', 'Contacts', 'Cookies', 'Documents', 'Downloads', 'example.py', 'exception_handling.ipynb', 'Favorites', 'Instagram.lnk', 'IntelGraphicsProfiles', 'Jedi', 'Links', 'Local Settings', 'mah.txt.ipynb', 'mathop.py', 'Music', 'My Documents', 'my pacakages1.py', 'my pacakages2.py', 'my packages1.py', 'my packages2.py', 'mypackages3.py', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{987f0b07-9de4-11f0-b62e-facbbbddfca2}.TxR.0.regtrans-ms', 'NTUSER.DAT{987f0b07-9de4-11f0-b62e-facbbbddfca2}.TxR.1.regtrans-ms', 'NTUSER.DAT{987f0b07-9de4-11f0-b62e-facbbbddfca2}.TxR.2.regtrans-ms', 'NTUSER.DAT{987f0b07-9de4-11f0-b62e-facbbbddfca2}.TxR.blf', 'NTUSER.DAT{987f0b08-9de4-11f0-b62e-facbbbddfca2}.TM.blf', 'NTUSER.DAT{987f0b08-9de4-11f0-b62e-facbbbddfca2}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{987f0b08-9de4-11f0-b62e-facbbbddfca2}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'p8.py', 'pacakages2.py', 'pacakages4.py', 'pacakages6.py', 'pacakges7.py', 'Pandas.ipynb', 'panda_da_jun18.ipynb', 'parctical 8.png', 'pr1(1).py', 'pr1(3).py', 'pr2(1).py', 'pr2(1.1).py', 'pr2(2).py', 'pr2.py', 'pr3(1).py', 'pr4(1).py', 'pr41.1(1).py', 'pr5(1).java', 'practice questions.ipynb', 'PrintHood', 'python1.py', 'Recent', 'sample.txt', 'sample.txt.ipynb', 'Saved Games', 'Searches', 'SendTo', 'Start Menu', 'student.csv', 'Templates', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled10.ipynb', 'Untitled11.ipynb', 'Untitled12.ipynb', 'Untitled13.ipynb', 'Untitled14.ipynb', 'Untitled15.ipynb', 'Untitled16.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Untitled5.ipynb', 'Untitled6.ipynb', 'Untitled7.ipynb', 'Untitled8.ipynb', 'Untitled9.ipynb', 'Videos', 'weekly assignment2.ipynb', '__pycache__']

In [8]:
import pandas as pd

df = pd.read_csv("student.csv")

df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [9]:
df.shape

(10, 5)

In [10]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [11]:
# student1.csv

In [13]:
import urllib.request

url = "https://raw.githubusercontent.com/AdityaThakare72/interns-may-2026/master/daily_codes/week4/student1.csv"

urllib.request.urlretrieve(url, "student1.csv")

print("Downloaded")

Downloaded

In [14]:
import pandas as pd

df = pd.read_csv("student1.csv")
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [15]:
col = ['roll', 'name', 'class', 'marks', 'age']

In [17]:
df = pd.read_csv('student1.csv', names = col)
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [18]:
# student3.tsv

In [22]:
import urllib.request

url = "https://raw.githubusercontent.com/AdityaThakare72/interns-may-2026/master/daily_codes/week4/student3.tsv"

urllib.request.urlretrieve(url, "student3.tsv")

print("Downloaded")

Downloaded

In [ ]:
df = pd.read_csv(''student3.tsv)